version: 2.1
jobs:
 build:
   machine: true
   steps:
     - checkout
     # build the application image
     - run: 
            name: docker image build 
            command: docker build -t bengotch/simplewhale:$CIRCLE_BRANCH .
